# Generated by Django 4.0.4 on 2022-04-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typ_dania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='danie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_dania', models.CharField(max_length=20)),
                ('typ_dania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.typ_dania')),
            ],
        ),
    ]
